<a href="https://colab.research.google.com/github/sarwathasan72-svg/Masai_IIT_AIML/blob/main/Data_Splitting_and_Validation_Protocols.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.DataFrame({
    "Hours" : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
    "Marks" :[20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210]

})

df

hi

    Hours  Marks
0       1     20
1       2     30
2       3     40
3       4     50
4       5     60
5       6     70
6       7     80
7       8     90
8       9    100
9      10    110
10     11    120
11     12    130
12     13    140
13     14    150
14     15    160
15     16    170
16     17    180
17     18    190
18     19    200
19     20    210

In [ ]:
# Step 2: Separate features (X) from target (y)
# TODO: X should be a DataFrame (double brackets); y should be a Series

x = df[["Hours"]]
y = df[["Marks"]]
y

    Marks
0      20
1      30
2      40
3      50
4      60
5      70
6      80
7      90
8     100
9     110
10    120
11    130
12    140
13    150
14    160
15    170
16    180
17    190
18    200
19    210

In [ ]:
# Step 3: First split — 70% train, 30% temporary holdout
# TODO: call train_test_split with test_size=0.3, random_state=42

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.3,
    random_state=42

)


x_val, x_test, y_val, y_test = train_test_split(
    x_test,
    y_test,
    test_size=0.5,
    random_state=42
)

# print("Training rows:", len(x_train))
# print("Validation rows:", len(x_val))
# print("Testing rows:", len(x_test))

print("X_Train: ", x_train.shape[0])
print("X Val", x_val)
print("X Test", x_test)

X_Train:  14
X Val     Hours
15     16
8       9
1       2
X Test     Hours
0       1
17     18
5       6

In [23]:
import pandas as pd
from io import StringIO

df = pd.read_csv("/content/sample_data/study_hours.csv")
# df = pd.read_csv(StringIO(study_hours.csv))
df.head()
df.count()

df.describe()

             Hours        Marks
count  2000.000000  2000.000000
mean    102.424000  1022.343000
std      57.282492   567.800799
min       1.000000    24.000000
25%      54.000000   532.500000
50%     102.000000  1020.000000
75%     153.000000  1505.250000
max     200.000000  2008.000000