<a href="https://colab.research.google.com/github/sarwathasan72-svg/Masai_IIT_AIML/blob/main/E2E_ML_Learning_Pipeline_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID":[101,102,103,104,105,106,107,108,109,110],

    "Gender":[
        "Male","Female","Female","Male","Male",
        "Female","Male","Female","Male","Female"
    ],

    "Department":[
        "CS","IT","CS","ECE","IT",
        "CS","ECE","IT","CS","ECE"
    ],

    "Study_Hours":[
        2,5,7,3,np.nan,
        6,4,9,np.nan,5
    ],

    "Attendance":[
        60,82,91,70,95,
        88,75,98,80,np.nan
    ],

    "Assignments":[
        3,7,8,5,9,
        8,6,10,7,6
    ],

    "Previous_Score":[
        55,72,85,60,90,
        82,65,95,78,70
    ],

    "Sports":[
        "Yes","No","No","Yes","No",
        "No","Yes","No","Yes","No"
    ],

    "Pass":[
        0,1,1,0,1,
        1,0,1,1,0
    ]
})

print(df)

   Student_ID  Gender Department  Study_Hours  Attendance  Assignments  \
0         101    Male         CS          2.0        60.0            3
1         102  Female         IT          5.0        82.0            7
2         103  Female         CS          7.0        91.0            8
3         104    Male        ECE          3.0        70.0            5
4         105    Male         IT          NaN        95.0            9
5         106  Female         CS          6.0        88.0            8
6         107    Male        ECE          4.0        75.0            6
7         108  Female         IT          9.0        98.0           10
8         109    Male         CS          NaN        80.0            7
9         110  Female        ECE          5.0         NaN            6

   Previous_Score Sports  Pass
0              55    Yes     0
1              72     No     1
2              85     No     1
3              60    Yes     0
4              90     No     1
5              82     No     1
6              65    Yes     0
7              95     No     1
8              78    Yes     1
9              70     No     0

In [4]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.0,60.0,3,55,Yes,0
1,102,Female,IT,5.0,82.0,7,72,No,1
2,103,Female,CS,7.0,91.0,8,85,No,1
3,104,Male,ECE,3.0,70.0,5,60,Yes,0
4,105,Male,IT,8.0,95.0,9,90,No,1
5,106,Female,CS,6.0,88.0,8,82,No,1
6,107,Male,ECE,4.0,75.0,6,65,Yes,0
7,108,Female,IT,9.0,98.0,10,95,No,1
8,109,Male,CS,NaN,80.0,7,78,Yes,1
9,110,Female,ECE,5.0,NaN,6,70,No,0

In [6]:
df.shape

(10, 9)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      10 non-null     int64
 1   Gender          10 non-null     object
 2   Department      10 non-null     object
 3   Study_Hours     9 non-null      float64
 4   Attendance      9 non-null      float64
 5   Assignments     10 non-null     int64
 6   Previous_Score  10 non-null     int64
 7   Sports          10 non-null     object
 8   Pass            10 non-null     int64
dtypes: float64(2), int64(4), object(3)
memory usage: 852.0+ bytes

In [15]:
df.isnull().sum()

Student_ID        0
Gender            0
Department        0
Study_Hours       2
Attendance        1
Assignments       0
Previous_Score    0
Sports            0
Pass              0
dtype: int64

In [18]:
df["Study_Hours"] = df["Study_Hours"].fillna(df["Study_Hours"].mean())

In [19]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000,60.0,3,55,Yes,0
1,102,Female,IT,5.000,82.0,7,72,No,1
2,103,Female,CS,7.000,91.0,8,85,No,1
3,104,Male,ECE,3.000,70.0,5,60,Yes,0
4,105,Male,IT,5.125,95.0,9,90,No,1
5,106,Female,CS,6.000,88.0,8,82,No,1
6,107,Male,ECE,4.000,75.0,6,65,Yes,0
7,108,Female,IT,9.000,98.0,10,95,No,1
8,109,Male,CS,5.125,80.0,7,78,Yes,1
9,110,Female,ECE,5.000,NaN,6,70,No,0

In [20]:
df_female = df[df["Gender"] =="Female"]
df_female

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
1,102,Female,IT,5.0,82.0,7,72,No,1
2,103,Female,CS,7.0,91.0,8,85,No,1
5,106,Female,CS,6.0,88.0,8,82,No,1
7,108,Female,IT,9.0,98.0,10,95,No,1
9,110,Female,ECE,5.0,NaN,6,70,No,0

In [21]:
df_female_mean = df_female["Attendance"].mean()
df_female_mean

np.float64(89.75)

In [26]:
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000,60.0,3,55,Yes,0
1,102,Female,IT,5.000,82.0,7,72,No,1
2,103,Female,CS,7.000,91.0,8,85,No,1
3,104,Male,ECE,3.000,70.0,5,60,Yes,0
4,105,Male,IT,5.125,95.0,9,90,No,1
5,106,Female,CS,6.000,88.0,8,82,No,1
6,107,Male,ECE,4.000,75.0,6,65,Yes,0
7,108,Female,IT,9.000,98.0,10,95,No,1
8,109,Male,CS,5.125,80.0,7,78,Yes,1
9,110,Female,ECE,5.000,NaN,6,70,No,0

In [33]:
df_female_mean = df_female["Attendance"].mean()
df_female_mean

np.float64(89.75)

In [37]:
df["attnedance"] = df["Attendance"].fillna(df_female_mean)
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass,attnedance
0,101,Male,CS,2.000,60.000000,3,55,Yes,0,60.000000
1,102,Female,IT,5.000,82.000000,7,72,No,1,82.000000
2,103,Female,CS,7.000,91.000000,8,85,No,1,91.000000
3,104,Male,ECE,3.000,70.000000,5,60,Yes,0,70.000000
4,105,Male,IT,5.125,95.000000,9,90,No,1,95.000000
5,106,Female,CS,6.000,88.000000,8,82,No,1,88.000000
6,107,Male,ECE,4.000,75.000000,6,65,Yes,0,75.000000
7,108,Female,IT,9.000,98.000000,10,95,No,1,98.000000
8,109,Male,CS,5.125,80.000000,7,78,Yes,1,80.000000
9,110,Female,ECE,5.000,82.111111,6,70,No,0,82.111111

In [35]:
df["attnedance"] = df["Attendance"].fillna(df_female_mean)
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass,attnedance
0,101,Male,CS,2.000,60.000000,3,55,Yes,0,60.000000
1,102,Female,IT,5.000,82.000000,7,72,No,1,82.000000
2,103,Female,CS,7.000,91.000000,8,85,No,1,91.000000
3,104,Male,ECE,3.000,70.000000,5,60,Yes,0,70.000000
4,105,Male,IT,5.125,95.000000,9,90,No,1,95.000000
5,106,Female,CS,6.000,88.000000,8,82,No,1,88.000000
6,107,Male,ECE,4.000,75.000000,6,65,Yes,0,75.000000
7,108,Female,IT,9.000,98.000000,10,95,No,1,98.000000
8,109,Male,CS,5.125,80.000000,7,78,Yes,1,80.000000
9,110,Female,ECE,5.000,82.111111,6,70,No,0,82.111111

In [29]:
df["Attendance"] = df["Attendance"].fillna(df['Attendance'].mean())
df

,Student_ID,Gender,Department,Study_Hours,Attendance,Assignments,Previous_Score,Sports,Pass
0,101,Male,CS,2.000,60.000000,3,55,Yes,0
1,102,Female,IT,5.000,82.000000,7,72,No,1
2,103,Female,CS,7.000,91.000000,8,85,No,1
3,104,Male,ECE,3.000,70.000000,5,60,Yes,0
4,105,Male,IT,5.125,95.000000,9,90,No,1
5,106,Female,CS,6.000,88.000000,8,82,No,1
6,107,Male,ECE,4.000,75.000000,6,65,Yes,0
7,108,Female,IT,9.000,98.000000,10,95,No,1
8,109,Male,CS,5.125,80.000000,7,78,Yes,1
9,110,Female,ECE,5.000,82.111111,6,70,No,0

In [10]:
import pandas as pd
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


csv_data = """Student ID,Gender,Department,Study Hours,Attendance,Assignments,Previous Score,Sports,Pass
1,Male,CS,3.0,85.0,4,72,False,1
2,Female,CS,2.5,88.5,3,65,True,0
3,Male,IT,,90.0,5,80,False,1
4,Female,Math,4.0,91.0,6,88,False,1
5,Male,CS,1.5,70.0,2,55,True,0
6,Female,IT,3.5,89.75,5,78,False,1
7,Male,Math,2.0,75.0,3,62,True,0
8,Female,CS,2.0,,4,68,False,0
9,Male,IT,4.5,95.0,7,92,False,1
10,Male,CS,1.0,65.0,2,50,True,0"""

df = pd.read_csv(StringIO(csv_data))

df

# Step 1: Fill missing Study Hours with the global column mean
# TODO: compute mean of 'Study Hours' and use fillna


# Step 2: Fill missing Attendance using the female-subgroup mean
# TODO: filter to female rows, compute their mean Attendance, apply fillna

# Step 3: Create the Hours per Assignment feature column
# TODO: add new column = Study Hours / Assignments

# Step 4: Define X (five numerical features) and y (Pass)
# TODO: select the five specified columns into X
# TODO: set y = Pass column

# Step 5: Perform the train-test split (test_size=0.3, random_state=42)
# TODO: call train_test_split

# Step 6: Train a LogisticRegression model (max_iter=1000)
# TODO: instantiate model, call fit on training split

# Step 7: Print predictions and actual labels for the test split
# TODO: call predict on X_test, print predictions and y_test.values

,Student ID,Gender,Department,Study Hours,Attendance,Assignments,Previous Score,Sports,Pass
0,1,Male,CS,3.0,85.00,4,72,False,1
1,2,Female,CS,2.5,88.50,3,65,True,0
2,3,Male,IT,NaN,90.00,5,80,False,1
3,4,Female,Math,4.0,91.00,6,88,False,1
4,5,Male,CS,1.5,70.00,2,55,True,0
5,6,Female,IT,3.5,89.75,5,78,False,1
6,7,Male,Math,2.0,75.00,3,62,True,0
7,8,Female,CS,2.0,NaN,4,68,False,0
8,9,Male,IT,4.5,95.00,7,92,False,1
9,10,Male,CS,1.0,65.00,2,50,True,0

In [11]:
# Step 1: Fill missing Study Hours with the global column mean
# TODO: compute mean of 'Study Hours' and use fillna
global_mean = df["Study Hours"].mean()

df["Study Hours"] = df["Study Hours"].fillna(global_mean)
df

,Student ID,Gender,Department,Study Hours,Attendance,Assignments,Previous Score,Sports,Pass
0,1,Male,CS,3.000000,85.00,4,72,False,1
1,2,Female,CS,2.500000,88.50,3,65,True,0
2,3,Male,IT,2.666667,90.00,5,80,False,1
3,4,Female,Math,4.000000,91.00,6,88,False,1
4,5,Male,CS,1.500000,70.00,2,55,True,0
5,6,Female,IT,3.500000,89.75,5,78,False,1
6,7,Male,Math,2.000000,75.00,3,62,True,0
7,8,Female,CS,2.000000,NaN,4,68,False,0
8,9,Male,IT,4.500000,95.00,7,92,False,1
9,10,Male,CS,1.000000,65.00,2,50,True,0

In [20]:
# Step 2: Fill missing Attendance using the female-subgroup mean
# TODO: filter to female rows, compute their mean Attendance, apply fillna

# female_attendance_mean = femaledf["Attendance"].mean
female_attendance_mean = df.loc[df["Gender"]=="Female","Attendance"].mean()

df.loc[df["Gender"] == "Female", "Attendance"] = (df.loc[df["Gender"] == "Female","Attendance"].fillna(female_attendance_mean))
df

,Student ID,Gender,Department,Study Hours,Attendance,Assignments,Previous Score,Sports,Pass
0,1,Male,CS,3.000000,85.00,4,72,False,1
1,2,Female,CS,2.500000,88.50,3,65,True,0
2,3,Male,IT,2.666667,90.00,5,80,False,1
3,4,Female,Math,4.000000,91.00,6,88,False,1
4,5,Male,CS,1.500000,70.00,2,55,True,0
5,6,Female,IT,3.500000,89.75,5,78,False,1
6,7,Male,Math,2.000000,75.00,3,62,True,0
7,8,Female,CS,2.000000,89.75,4,68,False,0
8,9,Male,IT,4.500000,95.00,7,92,False,1
9,10,Male,CS,1.000000,65.00,2,50,True,0

In [22]:
# Step 3: Create the Hours per Assignment feature column
# TODO: add new column = Study Hours / Assignments

df["Hours_per_Assignment"] = df["Study Hours"]/df["Assignments"]
df

,Student ID,Gender,Department,Study Hours,Attendance,Assignments,Previous Score,Sports,Pass,Hours_per_Assignment
0,1,Male,CS,3.000000,85.00,4,72,False,1,0.750000
1,2,Female,CS,2.500000,88.50,3,65,True,0,0.833333
2,3,Male,IT,2.666667,90.00,5,80,False,1,0.533333
3,4,Female,Math,4.000000,91.00,6,88,False,1,0.666667
4,5,Male,CS,1.500000,70.00,2,55,True,0,0.750000
5,6,Female,IT,3.500000,89.75,5,78,False,1,0.700000
6,7,Male,Math,2.000000,75.00,3,62,True,0,0.666667
7,8,Female,CS,2.000000,89.75,4,68,False,0,0.500000
8,9,Male,IT,4.500000,95.00,7,92,False,1,0.642857
9,10,Male,CS,1.000000,65.00,2,50,True,0,0.500000

In [28]:
# Step 4: Define X (five numerical features) and y (Pass)
# TODO: select the five specified columns into X
# TODO: set y = Pass column

X = df[
    [
        "Study Hours",
        "Attendance",
        "Assignments",
        "Previous Score",
        "Hours_per_Assignment"
        ]
    ]

X
y = df["Pass"]
y

0    1
1    0
2    1
3    1
4    0
5    1
6    0
7    0
8    1
9    0
Name: Pass, dtype: int64

In [33]:
# Step 5: Perform the train-test split (test_size=0.3, random_state=42)
# TODO: call train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size =0.3,
    random_state =42
)

8    1
1    0
5    1
Name: Pass, dtype: int64

In [ ]:
# Step 6: Train a LogisticRegression model (max_iter=1000)
# TODO: instantiate model, call fit on training split