<a href="https://colab.research.google.com/github/sarwathasan72-svg/Masai_IIT_AIML/blob/main/Integrated_Data_Preparation_Workshop_Subjective.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

data = {
    "student_id": [201, 202, 203, 204, 205, 206, 207, 201],
    "gender": ["male", "female", "male", "female", "male", "female", "male", "male"],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune", "Delhi", "Delhi"],
    "age": [18, 20, None, 22, 19, None, 20, 18],
    "hours_studied": [5, 4, 6, 3, 5, 4, 4, 5],
    "attendance": [90, 95, 70, 92, 78, 96, 85, 90],
    "previous_marks": [75, 80, 60, 88, 68, 85, 70, 75],
    "placement": ["yes", "no", "yes", "no", "yes", "no", "no", "yes"],
}

df = pd.DataFrame(data)

    # Step 1: identify target and feature columns
    # TODO: exclude the identifier column from the feature set

    # Step 2: remove duplicate rows without inplace=True
    # TODO: your code here

    # Step 3: fill missing ages and convert to int
    # TODO: your code here

    # Step 4: engineer study_efficiency and high_attendance
    # TODO: your code here

    # Step 5: groupby summaries and gender distribution
    # TODO: your code here

df  # or a dict/tuple of results, as you see fit

# if __name__ == "__main__":
#     result = prepare_data(data)
#     print(result)

,student_id,gender,city,age,hours_studied,attendance,previous_marks,placement
0,201,male,Delhi,18.0,5,90,75,yes
1,202,female,Mumbai,20.0,4,95,80,no
2,203,male,Pune,NaN,6,70,60,yes
3,204,female,Delhi,22.0,3,92,88,no
4,205,male,Mumbai,19.0,5,78,68,yes
5,206,female,Pune,NaN,4,96,85,no
6,207,male,Delhi,20.0,4,85,70,no
7,201,male,Delhi,18.0,5,90,75,yes

In [14]:

    # Step 1: identify target and feature columns
    # TODO: exclude the identifier column from the feature set

target = "placement"
df = df.drop(columns=["student_id", target])
df

   gender    city   age  hours_studied  attendance  previous_marks
0    male   Delhi  18.0              5          90              75
1  female  Mumbai  20.0              4          95              80
2    male    Pune   NaN              6          70              60
3  female   Delhi  22.0              3          92              88
4    male  Mumbai  19.0              5          78              68
5  female    Pune   NaN              4          96              85
6    male   Delhi  20.0              4          85              70
7    male   Delhi  18.0              5          90              75

In [15]:
    # Step 2: remove duplicate rows without inplace=True
    # TODO: your code here


df = pd.DataFrame(data)

# df.duplicated().sum()

df = df.drop_duplicates()
df

,student_id,gender,city,age,hours_studied,attendance,previous_marks,placement
0,201,male,Delhi,18.0,5,90,75,yes
1,202,female,Mumbai,20.0,4,95,80,no
2,203,male,Pune,NaN,6,70,60,yes
3,204,female,Delhi,22.0,3,92,88,no
4,205,male,Mumbai,19.0,5,78,68,yes
5,206,female,Pune,NaN,4,96,85,no
6,207,male,Delhi,20.0,4,85,70,no

In [18]:
   # Step 3: fill missing ages and convert to int
    # TODO: your code here

df["age"] = df["age"].fillna(df["age"].mean()).astype(int)
df

,student_id,gender,city,age,hours_studied,attendance,previous_marks,placement
0,201,male,Delhi,18,5,90,75,yes
1,202,female,Mumbai,20,4,95,80,no
2,203,male,Pune,19,6,70,60,yes
3,204,female,Delhi,22,3,92,88,no
4,205,male,Mumbai,19,5,78,68,yes
5,206,female,Pune,19,4,96,85,no
6,207,male,Delhi,20,4,85,70,no

In [24]:
 # Step 4: engineer study_efficiency and high_attendance
    # TODO: your code here

df["study_efficiency"] = df["previous_marks"] / df["hours_studied"]
df

KeyError: 'previous_marks'